### PR TITLE
Create build.yml

### PR DESCRIPTION
**Pull request by Neubulae**
cuz why not :ioa:

### CODE REVIEW

**Comment by Neubulae** [comment]
fuck I just notice u have no gradlew kill me

**Comment by Devan-Kerman** [comment]
what does this do

**Comment by Neubulae** [comment]
> what does this do

build

**Comment by Devan-Kerman** [comment]
seems legit

**Comment by Devan-Kerman** [comment]
what happened now

**Comment by Devan-Kerman** [comment]
oh that is epic I can press the build button

**Pull request merged**
